const newCustomerEventProps = {
    $set: {
        created: 1615478426,
        currency: 'usd',
        customer_name: null,
        distinct_id: 'cus_J632IbQFZfXXt5',
        has_active_subscription: true
    },
    created: 1615478426,
    currency: 'usd',
    customer_name: null,
    distinct_id: 'cus_J632IbQFZfXXt5',
    has_active_subscription: true,
    subscription0__billing_cycle_anchor: 1614708845,
    subscription0__cancel_at_period_end: false,
    subscription0__collection_method: 'charge_automatically',
    subscription0__created: 1614708845,
    subscription0__current_period_end: 1617387245,
    subscription0__current_period_start: 1614708845,
    subscription0__customer: 'cus_IuiXChYGDqmHPi',
    subscription0__id: 'sub_J2i9v9VdhWbjju',
    subscription0__items__data__0__created: 1614708846,
    subscription0__items__data__0__id: 'si_J2i9eUttdXoSlA',
    subscription0__items__data__0__metadata: {},
    subscription0__items__data__0__object: 'subscription_item',
    subscription0__items__data__0__price__active: true,
    subscription0__items__data__0__price__billing_scheme: 'tiered',
    subscription0__items__data__0__price__created: 1612865164,
    subscription0__items__data__0__price__currency: 'usd',
    subscription0__items__data__0__price__id: 'price_1IIt6eEuIatRXSdz0WhjQeI2',
    subscription0__items__data__0__price__livemode: false,
    subscription0__items__data__0__price__metadata: {},
    subscription0__items__data__0__price__object: 'price',
    subscription0__items__data__0__price__product: 'prod_IuiXiNy8CGzEj7',
    subscription0__items__data__0__price__recurring__aggregate_usage: 'sum',
    subscription0__items__data__0__price__recurring__interval: 'month',
    subscription0__items__data__0__price__recurring__interval_count: 1,
    subscription0__items__data__0__price__recurring__usage_type: 'metered',
    subscription0__items__data__0__price__tiers_mode: 'graduated',
    subscription0__items__data__0__price__type: 'recurring',
    subscription0__items__data__0__subscription: 'sub_J2i9v9VdhWbjju',
    subscription0__items__has_more: false,
    subscription0__items__object: 'list',
    subscription0__items__url: '/v1/subscription_items?subscription=sub_J2i9v9VdhWbjju',
    subscription0__latest_invoice: 'in_1IQcjREuIatRXSdzPq5XJFsQ',
    subscription0__livemode: false,
    subscription0__metadata: {},
    subscription0__object: 'subscription',
    subscription0__start_date: 1614708845,
    subscription0__status: 'active'
}

module.exports = {
    newCustomerEventProps
}
