name: Unit Tests

on:
    push:

jobs:
    build:
        name: Jest Tests
        runs-on: ubuntu-latest
        steps:
            # Check out the repository
            - uses: actions/checkout@v1

            # Install Node.js
            - uses: actions/setup-node@v1
              with:
                  node-version: 18.12.1
                  cache: "yarn"

            # Install dependencies
            - run: yarn

            # Run jest tests
            - run: yarn test
